# Generated by Django 6.1 on 2026-08-22 09:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                ("city", models.CharField(max_length=120, verbose_name="city")),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="district"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "rooms",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="rooms",
                    ),
                ),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("studio", "Studio"),
                            ("room", "Room"),
                            ("other", "Other"),
                        ],
                        default="apartment",
                        max_length=20,
                        verbose_name="housing type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "listing",
                "verbose_name_plural": "listings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["city"], name="listing_lis_city_6fde78_idx"),
                    models.Index(
                        fields=["housing_type"], name="listing_lis_housing_818560_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="listing_lis_is_acti_000111_idx"
                    ),
                    models.Index(fields=["price"], name="listing_lis_price_11ce52_idx"),
                    models.Index(
                        fields=["created_at"], name="listing_lis_created_bcc050_idx"
                    ),
                ],
            },
        ),
    ]
