# Generated by Django 6.1 on 2026-08-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="listings/", verbose_name="image"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="position"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listing.listing",
                        verbose_name="listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "listing image",
                "verbose_name_plural": "listing images",
                "ordering": ["position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "position"],
                        name="listing_lis_listing_5a987e_idx",
                    )
                ],
            },
        ),
    ]
