# Generated by Django 6.1 on 2026-08-23 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0002_listingimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="postal code"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["postal_code"], name="listing_lis_postal__6843bd_idx"
            ),
        ),
    ]
