# Generated by Django 6.1 on 2026-09-11 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0004_alter_listing_rooms_integer"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="max_booking_days_ahead",
            field=models.PositiveSmallIntegerField(
                default=365,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1095),
                ],
                verbose_name="maximum booking days ahead",
            ),
        ),
    ]
