# Generated by Django 6.1 on 2026-09-07 09:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def populate_price_per_night(apps, schema_editor):
    booking_model = apps.get_model("bookings", "Booking")

    for booking in booking_model.objects.select_related("listing"):
        booking.price_per_night = booking.listing.price
        booking.save(update_fields=["price_per_night"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price per night'),
        ),
        migrations.RunPython(populate_price_per_night, migrations.RunPython.noop),
    ]
