# Generated by Django 6.1 on 2026-09-07 08:56

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_rating_to_categories(apps, schema_editor):
    review_model = apps.get_model("reviews", "Review")

    for review in review_model.objects.all():
        category_rating = max(1, min(10, int(Decimal(review.rating) * Decimal("2"))))
        review.expectations_rating = category_rating
        review.cleanliness_rating = category_rating
        review.location_rating = category_rating
        review.rating = Decimal(category_rating).quantize(Decimal("0.01"))
        review.save(
            update_fields=[
                "expectations_rating",
                "cleanliness_rating",
                "location_rating",
                "rating",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('listing', '0004_alter_listing_rooms_integer'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cleanliness_rating',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='cleanliness rating'),
        ),
        migrations.AddField(
            model_name='review',
            name='expectations_rating',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='expectations rating'),
        ),
        migrations.AddField(
            model_name='review',
            name='location_rating',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='location rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=4, verbose_name='rating'),
        ),
        migrations.RunPython(migrate_rating_to_categories, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['listing', 'expectations_rating'], name='reviews_rev_listing_7a2d58_idx'),
        ),
    ]
