# Generated by Django 6.1 on 2026-09-07 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('listing', '0004_alter_listing_rooms_integer'),
        ('reviews', '0002_review_cleanliness_rating_review_expectations_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('listing', 'user'), name='unique_review_per_user_listing'),
        ),
    ]
